In [1]:
################## Lets start learning Numpy ########################


## numpy is a multidimesional array library 
# you can use it in 1d array , 2d array and 3 d array


# list are slow and numpy is fast

# list use a built in type for int and for that we have size, ref count , onjject type and object value 
# so that object will take a long longer size  but it require a  lot more space than numpy

# numpy uses less byte in memory and so that it is faster that regards 
# for numpy arry we have fastre to read less bytes of memory 
# no type checking when iterating trhoough objects


# numpy uses contiguous memory 
 # in list we have scatter around memory but those memory blocks are not necessary together 
 #but in numpy all the info are together in continious next to each other , so you can get the data faster and it is reliable 
 
 # all the memory blocks are next to each otehr , so you know how much of the memory block you  need for the array 
 
 # benifits of numpy 
 # cpu vpu are using the single instruction multiple data sind vector processing in 
 # more efffective cache utiliztion 
 



# how list are difffenet fom numpy 


# you can perform all of the list operations but can do more in numpy then list 

# you can not multiply lists together it will throw an error but you can perfrom that operation on numpy 

# application of numpy 
# mathematics but you should use 


#plotting 

# backend - Pandas , connect4m digital photography 

# machine Learning 



In [2]:
import numpy as np 

In [25]:
# define a array

a = np.array([1,2,3,4],dtype='int64')
a

array([1, 2, 3, 4])

In [26]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# get dimension 

b.ndim

2

In [28]:
a.ndim

1

In [29]:
b.shape

(2, 3)

In [30]:
a.shape

(4,)

In [31]:
a.dtype

dtype('int64')

In [32]:
# get size 
a.itemsize


8

In [34]:
b.itemsize

8

In [35]:
# total size = 
a.nbytes

32

In [36]:
b.nbytes

48

In [38]:
## accessing / changing specific elements . rows, columns

In [39]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [42]:
# get a specific element using rows , column

a[0,-1]

np.int64(7)

In [47]:
### get a specific row 

a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [48]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# getting little more fancy
# start end step 



In [51]:
a [0,0:5:2]

array([1, 3, 5])

In [52]:
a[1,5] = 20

In [53]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [57]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [58]:
b


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#### gett specific here 


b[0,1,1]

np.int64(4)

In [61]:

b[1,1,1] # it will give use 8

np.int64(8)

In [62]:
b.ndim

3

In [63]:
################## Initializing diff types of arrays


In [67]:
np.zeros((2,2,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [68]:
##### all ones

np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [70]:
### any other numbner

np.full((5,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [72]:
######### full like method 

np.full_like(b.shape,4)

array([4, 4, 4])

In [76]:
########## rendom decimal numbers
np.random.rand(4,2,3)

array([[[0.82852861, 0.04031355, 0.03927596],
        [0.33430669, 0.69461263, 0.34247862]],

       [[0.16440527, 0.6286434 , 0.53681122],
        [0.60829033, 0.20175067, 0.3454107 ]],

       [[0.15731601, 0.02800186, 0.61479008],
        [0.76715285, 0.57250726, 0.67319626]],

       [[0.25906015, 0.13075379, 0.32046001],
        [0.51353334, 0.84560732, 0.93037438]]])

In [77]:
np.random.random_sample(b.shape)

array([[[0.98208556, 0.29574485],
        [0.17518225, 0.61467811]],

       [[0.97187434, 0.21466556],
        [0.02979552, 0.14483346]]])

In [101]:
############### Random int
np.random.randint(9,size = (4,2))


array([[0, 8],
       [0, 7],
       [7, 1],
       [0, 8]], dtype=int32)

In [102]:
################## identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
# insert 

![Alt text for the image](images/array.png)



In [108]:
output = np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [117]:
output[1,1:4]=0
output[1:4,1:4]=0
output[2,2]=9
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
################ be careful coping arrays

a = np.array([1,2,3])
b = a.copy()
b[1] = 5
a

array([1, 2, 3])

In [121]:
a = np.array([1,2,3])
b = a
b[1] = 5
a

array([1, 5, 3])

In [122]:
############## Mathematics


a = np.array([1,2,3,4,5,6])
a+3

array([4, 5, 6, 7, 8, 9])

In [123]:
a*4

array([ 4,  8, 12, 16, 20, 24])

In [125]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [126]:
a-2

array([-1,  0,  1,  2,  3,  4])

In [128]:
a+=2

In [129]:
a

array([3, 4, 5, 6, 7, 8])

In [130]:
b = np.array([0,1,0,1,0])
a+b

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [131]:
b = np.array([0,1,0,1,0,1])
a+b

array([3, 5, 5, 7, 7, 9])

In [132]:
#################### Take sin #########
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ,
        0.98935825])

In [133]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029,  0.75390225,
       -0.14550003])

In [135]:
############################## Linear Algebra ######



a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [139]:
##### find the determinent 


c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [140]:
############## Statistics with numpy


stats = np.array([[0,1,2,3,4],[5,6,7,8,9]])
np.min(stats)

np.int64(0)

In [142]:
np.min(stats,axis=0)

array([0, 1, 2, 3, 4])

In [143]:
np.max(stats,axis = 1)

array([4, 9])

In [141]:
####################### what you  need to do as a early career engineer ######

In [ ]:
# Mastering the fundamentals  
# Learn from failure buiild to grow stronger 
# the power of good code , the first audinece is the next dev or may be you
# kiss , keep it simple , stupid  -- straight forward 
# consistancy is the key , make it like it is written by a single cohesive mind 
# write moduler , well organized code that can be changed later

# develop a quality mindset 
# testing is the most powerful tool in the engineer mind


# write a test for a safety net as it shows you wehre your code breasks 


# how do we act as leaving documnetation 

# ultimately it build mindset , keep it more quality  prevent bugs and understand the system 
# mastering the tools of your trade , solve the actual problems , become profecient with hyour system ,
# gain a deep understanding the esseential processes
# git  is the one , a clean version histroy for tracking down bugs ,
# debugging decipline with systmatic things
# solid documentation process is the things that save you countless hours of furstrutaion 
# never underestimate the power of communication skills , master those fundamentals --- 


# 0 clean code 
# quality mindset 
# Mastering tools 




In [144]:
################## REORGANIZING ARRAYS

In [145]:
before = np.array([[1,2,3,4],[5,6,7,8]])

print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [155]:
after = before.reshape((4,2,1))

In [156]:
print(after)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[7]
  [8]]]


In [157]:
# vertically stacking vectors


In [161]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [165]:
###### horizonatal stack 

np.hstack((v1,v2,v1))

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [169]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int64')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]]


In [172]:
################## aadvanced indexing 


filedata[filedata >= 20]

array([ 21, 196,  75,  34,  22,  33, 999,  78,  76,  88,  42,  33, 766,
        75,  55,  22,  33, 999,  78,  76,  88,  22,  33, 999,  78,  76,
        88,  42,  33, 766,  75,  55])

In [174]:
############## you can index with a list in numpy

a = np.array([1,2,33,45,67,45,45,46])
a[[0,1,6]]

array([ 1,  2, 45])

In [179]:
np.all(filedata >50,axis=1)

array([False, False, False, False, False, False])

In [180]:
arr = np.arange(1, 31).reshape(6, 5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [182]:
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [183]:
arr[0:4,1:5:1]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

In [184]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [187]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])